### ISSUE TITLE
Mailing lists

### ISSUE THREAD

**Issue by talllguy** [maptimebmore/set-up#6]
- [x] https://groups.google.com/forum/#!forum/maptime-organizers
- [x] https://groups.google.com/forum/#!forum/maptime-announce

**Comment by talllguy** [comment]
I'm signed up for both

**Comment by talllguy** [comment]
@RadadaJade Let me know when you sign up. @thisispayal you too! :)

**Comment by RadadaJade** [comment]
@talllguy I'm on both now!
