### ISSUE TITLE
chapters.json

### ISSUE THREAD

**Issue by talllguy** [maptimebmore/set-up#8]
Add us to [the map](https://github.com/maptime/maptime.github.io/blob/master/_data/chapters.json)!

**Comment by talllguy** [comment]
- [ ] Need to get @almccon to add me to the maptime org to edit that file.

**Comment by almccon** [comment]
Try pinging @geobrando or @geografa? I haven't added anybody to github lately, and I think they might have reorganized the groups structure...

**Comment by geobrando** [comment]
Hey @talllguy. Finally taking the plunge! Keep monitoring the issue created over in Maptime-admin for progress as we get you set up. If you want to jump ahead and add yourself to chapters.json, feel free to fork and submit a pull request using the existing entries as a template.

Also, you're welcome to use this organization but we'll also be setting up maptime/baltimore repo which will be used to create your webpage but can also be used for anything else.

**Comment by talllguy** [comment]
@geobrando alright, I'll fork and PR, no problem. I was just following the instructions ;) It looks like @geographa has gotten that setup now too https://github.com/maptime/maptime-admin/issues/132#issuecomment-131468557
